
name: "Django Deploy Crons"
description: "Package a Django project into a package for AWS Lambda"
inputs:
  application:
    description: "The tagged AWS name of your application"
    required: true
    default:
  environment:
    description: "The tagged environment name to deploy (i.e. dev, prod)"
    required: true
    default: 
  code:
    description: "The path to your project code (the directory containing manage.py)"
    required: true
    default:
  requirements:
    description: "The path to your pip requirements file"
    required: true
    default:
  bucket:
    description: "The name of your S3 bucket"
    require: true
    default:
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.application }}
    - ${{ inputs.environment }}
    - ${{ inputs.code }}
    - ${{ inputs.requirements }}
    - ${{ inputs.bucket }}
