
name: "Django Deploy Crons"
description: "Package a Django project into a package for AWS Lambda"
inputs:
  application:
    description: "The tagged AWS name of your application"
    required: true
    default:
  environment:
    description: "The tagged environment name to deploy (i.e. dev, prod)"
    required: true
    default: 
  code:
    description: "The path to your project code (the directory containing manage.py)"
    required: true
    default:
  requirements:
    description: "The path to your pip requirements file"
    required: true
    default:
  bucket:
    description: "The name of your S3 bucket"
    require: true
    default:
  zappa:
    description: "A boolean of whether this project is deployed using Zappa to determine if Django migrations should be run"
    require: false
    default: false
  include_files:
    description: "A comma-separated list of specific file paths to include (e.g., specific static files)"
    require: false
runs:
  using: "docker"
  image: docker://docker.io/thontechnology/deploy-django-crons:master
  args:
    - ${{ inputs.application }}
    - ${{ inputs.environment }}
    - ${{ inputs.code }}
    - ${{ inputs.requirements }}
    - ${{ inputs.bucket }}
    - ${{ inputs.zappa }}
    - ${{ inputs.include_files }}
